[versions]
android = "9.0.0"
navigation = "2.9.6"
retrofit = "3.0.0"

[libraries]
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
androidApp = { id = "com.android.application", version.ref = "android" }
androidLib = { id = "com.android.library", version.ref = "android" }
