[versions]
android = "8.13.0"
kotlin = "2.2.21"

[libraries]
androidx-test-core = "androidx.test:core-ktx:1.7.0"
androidx-test-rules = "androidx.test:rules:1.7.0"
androidx-test-runner = "androidx.test:runner:1.7.0"
androidx-test-ext = "androidx.test.ext:junit:1.3.0"
mockWebServer = "com.squareup.okhttp3:mockwebserver:5.2.1"

[bundles]
androidTest = ["androidx-test-rules", "androidx-test-runner", "androidx-test-ext", "androidx-test-core"]

[plugins]
androidApp = { id = "com.android.application", version.ref = "android" }
androidLib = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
